// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloaders

import (
	"github.com/RobusK/GoCtaApi/api"
	"sync"
	"time"
)

// PredictionLoaderConfig captures the config to create a new PredictionLoader
type PredictionLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []string) ([][]api.Prediction, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewabcLoader creates a new PredictionLoader given a fetch, wait, and maxBatch
func NewabcLoader(config PredictionLoaderConfig) *PredictionLoader {
	return &PredictionLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// PredictionLoader batches and caches requests
type PredictionLoader struct {
	// this method provides the data for the loader
	fetch func(keys []string) ([][]api.Prediction, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[string][]api.Prediction

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *PredictionLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type PredictionLoaderBatch struct {
	keys    []string
	data    [][]api.Prediction
	error   []error
	closing bool
	done    chan struct{}
}

// Load a []api.Prediction by key, batching and caching will be applied automatically
func (l *PredictionLoader) Load(key string) ([]api.Prediction, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a []api.Prediction.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *PredictionLoader) LoadThunk(key string) func() ([]api.Prediction, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() ([]api.Prediction, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &PredictionLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() ([]api.Prediction, error) {
		<-batch.done

		var data []api.Prediction
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *PredictionLoader) LoadAll(keys []string) ([][]api.Prediction, []error) {
	results := make([]func() ([]api.Prediction, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	Predictions := make([][]api.Prediction, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		Predictions[i], errors[i] = thunk()
	}
	return Predictions, errors
}

// LoadAllThunk returns a function that when called will block waiting for a []api.Predictions.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *PredictionLoader) LoadAllThunk(keys []string) func() ([][]api.Prediction, []error) {
	results := make([]func() ([]api.Prediction, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([][]api.Prediction, []error) {
		Predictions := make([][]api.Prediction, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			Predictions[i], errors[i] = thunk()
		}
		return Predictions, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *PredictionLoader) Prime(key string, value []api.Prediction) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		l.unsafeSet(key, value)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *PredictionLoader) Clear(key string) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *PredictionLoader) unsafeSet(key string, value []api.Prediction) {
	if l.cache == nil {
		l.cache = map[string][]api.Prediction{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *PredictionLoaderBatch) keyIndex(l *PredictionLoader, key string) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *PredictionLoaderBatch) startTimer(l *PredictionLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *PredictionLoaderBatch) end(l *PredictionLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
